// <auto-generated />
using System;
using MerittRestuarant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MerittRestuarant.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215000715_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MerittRestuarant.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MerittRestuarant.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Appetizers"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Main Courses"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Side Dish"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Beverages"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("MerittRestuarant.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Name = "Cayenne powder"
                        },
                        new
                        {
                            IngredientId = 2,
                            Name = "Salt"
                        },
                        new
                        {
                            IngredientId = 3,
                            Name = "Pine nuts"
                        },
                        new
                        {
                            IngredientId = 4,
                            Name = "Chicken"
                        },
                        new
                        {
                            IngredientId = 5,
                            Name = "Spinach"
                        },
                        new
                        {
                            IngredientId = 6,
                            Name = "Garlic"
                        },
                        new
                        {
                            IngredientId = 7,
                            Name = "Coconut aminos"
                        },
                        new
                        {
                            IngredientId = 8,
                            Name = "Olive oil"
                        },
                        new
                        {
                            IngredientId = 9,
                            Name = "Mushrooms"
                        },
                        new
                        {
                            IngredientId = 10,
                            Name = "Onion"
                        },
                        new
                        {
                            IngredientId = 11,
                            Name = "Coconut oil"
                        },
                        new
                        {
                            IngredientId = 12,
                            Name = "Nutritional yeast"
                        },
                        new
                        {
                            IngredientId = 13,
                            Name = "Chicken broth"
                        },
                        new
                        {
                            IngredientId = 14,
                            Name = "Coconut milk"
                        },
                        new
                        {
                            IngredientId = 15,
                            Name = "Polenta"
                        },
                        new
                        {
                            IngredientId = 16,
                            Name = "Broccoli"
                        },
                        new
                        {
                            IngredientId = 17,
                            Name = "Black cod"
                        },
                        new
                        {
                            IngredientId = 18,
                            Name = "Avocado oil"
                        },
                        new
                        {
                            IngredientId = 19,
                            Name = "Garlic powder"
                        },
                        new
                        {
                            IngredientId = 20,
                            Name = "Chicken seasoning"
                        },
                        new
                        {
                            IngredientId = 21,
                            Name = "Long grain brown rice"
                        },
                        new
                        {
                            IngredientId = 22,
                            Name = "Quinoa"
                        },
                        new
                        {
                            IngredientId = 23,
                            Name = "Sriracha mayo"
                        },
                        new
                        {
                            IngredientId = 24,
                            Name = "Brussel sprouts"
                        },
                        new
                        {
                            IngredientId = 25,
                            Name = "Salmon"
                        },
                        new
                        {
                            IngredientId = 26,
                            Name = "Cajun seasoning"
                        });
                });

            modelBuilder.Entity("MerittRestuarant.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MerittRestuarant.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MerittRestuarant.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2,
                            Description = "Air fried, tender chicken marinated in a spicy blend of cayenne powder and garlic.",
                            ImageUrl = "https://picsum.photos/id/292/200/300",
                            Name = "Air Fried Chicken",
                            Price = 12.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 3,
                            Description = "Brussel sprouts roasted to perfection, topped with sriracha mayo for an extra kick.",
                            ImageUrl = "https://picsum.photos/id/292/200/300",
                            Name = "Roasted Brussel Sprouts",
                            Price = 9.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Description = "A creammy polenta with mushrooms and spinach.",
                            ImageUrl = "https://picsum.photos/id/292/200/300",
                            Name = "Mushroom Spinach Polenta",
                            Price = 14.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "A buttery black cod marinated in a spicy blend of cayenne powder and garlic.",
                            ImageUrl = "https://picsum.photos/id/292/200/300",
                            Name = "Pan Fried Black Cod",
                            Price = 15.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "A spicy, pan fried salmon",
                            ImageUrl = "https://picsum.photos/id/292/200/300",
                            Name = "Cajun Salmon",
                            Price = 13.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            Description = "A garlicky rice quinoa mix.",
                            ImageUrl = "https://picsum.photos/id/292/200/300",
                            Name = "Garlic Rice",
                            Price = 7.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "A tender, roasted broccoli with sea salt.",
                            ImageUrl = "https://picsum.photos/id/292/200/300",
                            Name = "Roasted Broccoli",
                            Price = 8.99m,
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("MerittRestuarant.Models.ProductIngredient", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("ProductIngredientId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ProductIngredients");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IngredientId = 4,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 8,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 20,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 2,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 18,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 23,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 24,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 1,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 2,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 3,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 5,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 6,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 7,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 9,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 10,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 11,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 12,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 13,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 14,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 15,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 1,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 2,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 17,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 18,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 19,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 18,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 25,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 26,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 2,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 6,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 13,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 21,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 22,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 2,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 8,
                            ProductIngredientId = 0
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 16,
                            ProductIngredientId = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MerittRestuarant.Models.Order", b =>
                {
                    b.HasOne("MerittRestuarant.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MerittRestuarant.Models.OrderItem", b =>
                {
                    b.HasOne("MerittRestuarant.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerittRestuarant.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MerittRestuarant.Models.Product", b =>
                {
                    b.HasOne("MerittRestuarant.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MerittRestuarant.Models.ProductIngredient", b =>
                {
                    b.HasOne("MerittRestuarant.Models.Ingredient", "Ingredient")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerittRestuarant.Models.Product", "Product")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MerittRestuarant.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MerittRestuarant.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerittRestuarant.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MerittRestuarant.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MerittRestuarant.Models.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MerittRestuarant.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MerittRestuarant.Models.Ingredient", b =>
                {
                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("MerittRestuarant.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MerittRestuarant.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
